# Generated by Django 4.1 on 2023-07-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0004_admin_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='time',
        ),
        migrations.RemoveField(
            model_name='templates',
            name='template_time',
        ),
    ]
