# Generated by Django 4.1 on 2023-07-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0005_remove_categorie_time_remove_templates_template_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='categorie')),
                ('client_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client_alttag', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
