# Generated by Django 4.1 on 2023-07-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0006_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_image',
            field=models.ImageField(blank=True, null=True, upload_to='client'),
        ),
    ]
