# Generated by Django 4.1 on 2023-07-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0007_alter_client_client_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField(blank=True, default='', null=True)),
                ('name', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('contact_no', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default='admin@gmail.com', max_length=254, null=True)),
                ('status', models.CharField(blank=True, default=0, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_image', models.ImageField(blank=True, null=True, upload_to='testimonial')),
                ('testimonial_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('testimonial_position', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('testimonial_discription', models.TextField(blank=True, default='', null=True)),
                ('testimonial_status', models.CharField(blank=True, default=0, max_length=255, null=True)),
            ],
        ),
    ]
