# Generated by Django 4.1 on 2023-07-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0008_connect_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='connect_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
