# Generated by Django 4.1 on 2023-07-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0009_connect_connect_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='connect_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
