# Generated by Django 4.1 on 2023-07-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0010_connect_connect_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='testimonial_tag',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
