# Generated by Django 4.1 on 2023-07-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0012_admin_data_u_username_alter_admin_data_u_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('categori', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Theme.categorie')),
            ],
        ),
    ]
