# Generated by Django 4.1 on 2023-07-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0015_uploadedfile_temp_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='temp_devname',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
