# Generated by Django 4.1 on 2023-08-03 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0016_uploadedfile_temp_devname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie_features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailn_feature', models.TextField(blank=True, default='', null=True)),
                ('custome_feature', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('categori_feature_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Theme.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, default='', null=True)),
                ('content_position', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('categori_details_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Theme.categorie')),
            ],
        ),
    ]
